/* Isi dua nilai ini dari Supabase. Jangan pernah gunakan service_role key di browser. */
const CONFIG={SUPABASE_URL:"https://fezkloyliybbqqolqlep.supabase.co",SUPABASE_ANON_KEY:"sb_publishable__YlUCLzf65jfCu0cRWDL2Q_PLbaUMd2"};
const ready=!CONFIG.SUPABASE_URL.startsWith("YOUR_")&&!CONFIG.SUPABASE_ANON_KEY.startsWith("YOUR_");
const sb=ready?window.supabase.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_ANON_KEY):null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let products=[];
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const esc=x=>String(x??"").replace(/[&"<>]/g,m=>({"&":"&amp;",'"':"&quot;","<":"&lt;",">":"&gt;"}[m]));
function toast(x){$("#toast").textContent=x;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1800)}
function showApp(){$("#loginScreen").classList.add("hidden");$("#app").classList.remove("hidden")}
function showLogin(){$("#app").classList.add("hidden");$("#loginScreen").classList.remove("hidden")}
async function load(){if(!sb)return;const {data,error}=await sb.from("products").select("*").order("created_at",{ascending:false});if(error)return toast(error.message);products=data||[];$("#total").textContent=products.length;$("#active").textContent=products.filter(p=>p.is_active).length;$("#low").textContent=products.filter(p=>Number(p.stock)<=5).length;renderRecent();renderTable()}
function table(list){if(!list.length)return "<p class='muted'>Belum ada produk.</p>";return `<div class="table-wrap"><table class="table"><thead><tr><th></th><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Action</th></tr></thead><tbody>${list.map(p=>`<tr><td>${p.image_url?`<img class="thumb" src="${esc(p.image_url)}">`:"<div class='thumb'></div>"}</td><td><b>${esc(p.name)}</b><br><small>${esc(p.category)}</small></td><td>${money(p.price)}</td><td>${p.stock??0}</td><td>${p.is_active?"Active":"Hidden"}</td><td><div class="actions"><button data-edit="${p.id}">Edit</button><button class="del" data-del="${p.id}">Delete</button></div></td></tr>`).join("")}</tbody></table></div>`}
function bind(){ $$("[data-edit]").forEach(b=>b.onclick=()=>edit(b.dataset.edit));$$("[data-del]").forEach(b=>b.onclick=()=>del(b.dataset.del))}
function renderRecent(){ $("#recent").innerHTML=table(products.slice(0,5));bind()}
function renderTable(){const q=$("#search").value.toLowerCase(),c=$("#filter").value;$("#table").innerHTML=table(products.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!c||p.category===c)));bind()}
async function init(){if(!ready){$("#loginError").textContent="Isi SUPABASE_URL dan SUPABASE_ANON_KEY di admin.js terlebih dahulu.";return}const {data:{session}}=await sb.auth.getSession();if(session){showApp();load()}sb.auth.onAuthStateChange((_,s)=>s?showApp():showLogin())}
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="";const {error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)$("#loginError").textContent=error.message)};
$("#logout").onclick=()=>sb.auth.signOut();$("#refresh").onclick=load;$("#search").oninput=renderTable;$("#filter").onchange=renderTable;$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");
$$(".nav").forEach(b=>b.onclick=()=>{$$(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".view").forEach(x=>x.classList.add("hidden"));$(`#${b.dataset.view}View`).classList.remove("hidden");$("#title").textContent=b.dataset.view==="products"?"Products":"Dashboard";$("#sidebar").classList.remove("open")});
function openModal(p){$("#modal").classList.remove("hidden");$("#formError").textContent="";$("#id").value=p?.id||"";$("#modalTitle").textContent=p?"Edit product":"Add product";$("#name").value=p?.name||"";$("#category").value=p?.category||"Parfume";$("#price").value=p?.price||0;$("#stock").value=p?.stock||0;$("#image").value=p?.image_url||"";$("#desc").value=p?.description||"";$("#activeBox").checked=p?p.is_active:true}
function closeModal(){$("#modal").classList.add("hidden")}function edit(id){openModal(products.find(p=>String(p.id)===String(id)))}async function del(id){const p=products.find(x=>String(x.id)===String(id));if(!confirm(`Hapus "${p.name}"?`))return;const {error}=await sb.from("products").delete().eq("id",id);if(error)return toast(error.message);toast("Product deleted.");load()}
$("#add,#dashAdd").onclick=()=>openModal();$("#close,#cancel").onclick=closeModal;
$("#productForm").onsubmit=async e=>{e.preventDefault();$("#formError").textContent="";const id=$("#id").value,p={name:$("#name").value.trim(),category:$("#category").value,price:Number($("#price").value),stock:Number($("#stock").value),image_url:$("#image").value.trim()||null,description:$("#desc").value.trim()||null,is_active:$("#activeBox").checked};const r=id?await sb.from("products").update(p).eq("id",id):await sb.from("products").insert(p);if(r.error)return $("#formError").textContent=r.error.message;closeModal();toast(id?"Product updated.":"Product added.");load()};
init();
